[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"

[profile.default.overrides]
"lib/v2-core/**/*.sol" = { solc_version = "0.5.16" }
"lib/v2-periphery/**/*.sol" = { solc_version = "0.6.6" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
